<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [

            // ── GRINDING WHEELS ─────────────────────────────────────────────
            [
                'category_id' => 'grinding-wheels',
                'meta'        => 'Batu Gerinda',
                'title'       => 'Grinding Wheel A36 TBF – 230mm',
                'badge'       => 'Best Seller',
                'img'         => '',
                'desc'        => 'Batu gerinda aluminium oxide serbaguna untuk penggerindaan baja konstruksi dan besi cor. Ikatan vitrified memberikan kestabilan dimensi pada kecepatan tinggi.',
                'spec_label'  => 'Diameter',
                'spec_val'    => '230 mm',
                'rpm'         => '6,600',
                'material'    => 'Baja Karbon, Besi Cor',
            ],
            [
                'category_id' => 'grinding-wheels',
                'meta'        => 'Batu Gerinda',
                'title'       => 'Grinding Wheel A60 TBF – 150mm',
                'badge'       => null,
                'img'         => '',
                'desc'        => 'Roda gerinda presisi berbutir halus untuk sharpening tool, pisau mesin, dan komponen yang memerlukan toleransi dimensi ketat.',
                'spec_label'  => 'Diameter',
                'spec_val'    => '150 mm',
                'rpm'         => '9,500',
                'material'    => 'HSS, Tool Steel',
            ],
            [
                'category_id' => 'grinding-wheels',
                'meta'        => 'Batu Gerinda',
                'title'       => 'Depressed Center Wheel 27A – 180mm',
                'badge'       => null,
                'img'         => '',
                'desc'        => 'Roda gerinda cekung tipe 27 untuk angle grinder. Ideal untuk penggerindaan sudut sambungan las dan perapian permukaan baja.',
                'spec_label'  => 'Diameter',
                'spec_val'    => '180 mm',
                'rpm'         => '8,500',
                'material'    => 'Baja Struktural, Stainless',
            ],
            [
                'category_id' => 'grinding-wheels',
                'meta'        => 'Batu Gerinda',
                'title'       => 'Bench Grinding Wheel WA46 – 200mm',
                'badge'       => 'New',
                'img'         => '',
                'desc'        => 'Batu gerinda meja white aluminum oxide untuk pengasahan pahat bubut, mata bor, dan pisau dengan hasil tajam sempurna tanpa overheat.',
                'spec_label'  => 'Diameter',
                'spec_val'    => '200 mm',
                'rpm'         => '2,980',
                'material'    => 'HSS, Carbide Tip',
            ],

            // ── CUTTING DISCS ────────────────────────────────────────────────
            [
                'category_id' => 'cutting-discs',
                'meta'        => 'Mata Potong',
                'title'       => 'Inox Cutting Disc – 115×1.0mm',
                'badge'       => 'Best Seller',
                'img'         => '',
                'desc'        => 'Mata potong ultra-tipis 1.0mm khusus stainless steel. Potongan bersih, minim burr, tidak merusak lapisan oksida pelindung pada SS304/SS316.',
                'spec_label'  => 'Ketebalan',
                'spec_val'    => '1.0 mm',
                'rpm'         => '13,300',
                'material'    => 'Stainless Steel, Inox',
            ],
            [
                'category_id' => 'cutting-discs',
                'meta'        => 'Mata Potong',
                'title'       => 'Steel Cutting Disc – 230×1.9mm',
                'badge'       => null,
                'img'         => '',
                'desc'        => 'Mata potong baja karbon tinggi diameter besar untuk pemotongan besi hollow, besi siku, dan profil baja struktural dengan umur pakai panjang.',
                'spec_label'  => 'Ketebalan',
                'spec_val'    => '1.9 mm',
                'rpm'         => '6,600',
                'material'    => 'Baja Karbon, Besi Profil',
            ],
            [
                'category_id' => 'cutting-discs',
                'meta'        => 'Mata Potong',
                'title'       => 'Multi-Purpose Cutting Disc – 125×1.6mm',
                'badge'       => null,
                'img'         => '',
                'desc'        => 'Mata potong serba guna cocok untuk baja biasa, besi galvanis, dan aluminium. Formula abrasif hybrid memperpanjang usia pemakaian hingga 30%.',
                'spec_label'  => 'Ketebalan',
                'spec_val'    => '1.6 mm',
                'rpm'         => '12,200',
                'material'    => 'Baja, Galvanis, Aluminium',
            ],
            [
                'category_id' => 'cutting-discs',
                'meta'        => 'Mata Potong',
                'title'       => 'Diamond Cutting Blade – 125mm Turbo',
                'badge'       => 'Premium',
                'img'         => '',
                'desc'        => 'Pisau potong berlapis diamond tipe turbo untuk beton, keramik, granit, dan bata. Segment turbo memungkinkan pemotongan basah maupun kering.',
                'spec_label'  => 'Diameter',
                'spec_val'    => '125 mm',
                'rpm'         => '12,000',
                'material'    => 'Beton, Keramik, Granit',
            ],

            // ── FLAP DISCS ───────────────────────────────────────────────────
            [
                'category_id' => 'flap-discs',
                'meta'        => 'Flap Disc',
                'title'       => 'Flap Disc Zirconia 40# – 125mm',
                'badge'       => 'Best Seller',
                'img'         => '',
                'desc'        => 'Flap disc zirconia alumina grit kasar untuk grinding agresif pada baja ringan dan stainless. Suhu kerja rendah mencegah perubahan warna pada inox.',
                'spec_label'  => 'Grit',
                'spec_val'    => '#40',
                'rpm'         => '12,200',
                'material'    => 'Baja Ringan, Stainless',
            ],
            [
                'category_id' => 'flap-discs',
                'meta'        => 'Flap Disc',
                'title'       => 'Flap Disc Aluminium Oxide 80# – 125mm',
                'badge'       => null,
                'img'         => '',
                'desc'        => 'Flap disc medium grit untuk penggerindaan sekaligus finishing permukaan baja. Cocok untuk perapian bekas las dan persiapan permukaan sebelum coating.',
                'spec_label'  => 'Grit',
                'spec_val'    => '#80',
                'rpm'         => '12,200',
                'material'    => 'Baja, Bekas Las',
            ],
            [
                'category_id' => 'flap-discs',
                'meta'        => 'Flap Disc',
                'title'       => 'Flap Disc Ceramic 36# – 180mm',
                'badge'       => 'New',
                'img'         => '',
                'desc'        => 'Flap disc keramik abrasif generasi baru dengan kemampuan self-sharpening. Awet 3× lebih lama dari zirconia biasa, ideal untuk stainless berat dan titanium.',
                'spec_label'  => 'Grit',
                'spec_val'    => '#36',
                'rpm'         => '8,500',
                'material'    => 'Stainless Berat, Titanium',
            ],
            [
                'category_id' => 'flap-discs',
                'meta'        => 'Flap Disc',
                'title'       => 'Flap Disc Conical Type 29 – 115mm',
                'badge'       => null,
                'img'         => '',
                'desc'        => 'Flap disc tipe cekung (conical) sudut 29° untuk grinding di area kontur dan sudut sempit. Material removal rate tinggi dengan getaran minimal.',
                'spec_label'  => 'Grit',
                'spec_val'    => '#60',
                'rpm'         => '13,300',
                'material'    => 'Baja, Besi Cor',
            ],

            // ── SANDPAPER ────────────────────────────────────────────────────
            [
                'category_id' => 'sandpaper',
                'meta'        => 'Amplas',
                'title'       => 'Amplas Rol Kain 100# – Lebar 100mm',
                'badge'       => null,
                'img'         => '',
                'desc'        => 'Amplas berbasis kain fleksibel untuk pengamplasan manual dan mesin. Cocok untuk logam, kayu keras, dan finishing komponen mesin presisi.',
                'spec_label'  => 'Grit',
                'spec_val'    => '#100',
                'rpm'         => '-',
                'material'    => 'Logam, Kayu Keras',
            ],
            [
                'category_id' => 'sandpaper',
                'meta'        => 'Amplas',
                'title'       => 'Sandpaper Waterproof 240# – A4 Sheet',
                'badge'       => null,
                'img'         => '',
                'desc'        => 'Kertas amplas tahan air silicon carbide untuk wet sanding body mobil, dempul, dan cat primer. Hasil permukaan halus tanpa goresan dalam.',
                'spec_label'  => 'Grit',
                'spec_val'    => '#240',
                'rpm'         => '-',
                'material'    => 'Cat, Dempul, Body Kendaraan',
            ],
            [
                'category_id' => 'sandpaper',
                'meta'        => 'Amplas',
                'title'       => 'Velcro Sanding Disc 125mm – 5-Hole',
                'badge'       => 'Best Seller',
                'img'         => '',
                'desc'        => 'Amplas cakram velcro sistem 5 lubang untuk orbital sander. Sistem debu aktif menjaga permukaan bersih dan memperpanjang umur amplas.',
                'spec_label'  => 'Grit',
                'spec_val'    => '#120',
                'rpm'         => '12,000',
                'material'    => 'Kayu, MDF, Dempul',
            ],

            // ── WIRE BRUSHES ─────────────────────────────────────────────────
            [
                'category_id' => 'wire-brushes',
                'meta'        => 'Sikat Kawat',
                'title'       => 'Cup Brush Twisted Wire – 75mm',
                'badge'       => null,
                'img'         => '',
                'desc'        => 'Sikat cawan kawat baja terpilin untuk pembersihan karat dan scale tebal pada permukaan baja. Kawat terpilin memberikan tekanan kontak lebih tinggi.',
                'spec_label'  => 'Diameter',
                'spec_val'    => '75 mm',
                'rpm'         => '6,000',
                'material'    => 'Baja Berkarat, Weld Spatter',
            ],
            [
                'category_id' => 'wire-brushes',
                'meta'        => 'Sikat Kawat',
                'title'       => 'Flat Wire Brush – 115mm Stainless',
                'badge'       => null,
                'img'         => '',
                'desc'        => 'Sikat kawat datar berbahan stainless steel untuk pembersihan permukaan inox tanpa kontaminasi besi. Wajib untuk fabrikasi food-grade dan pharmaceutical.',
                'spec_label'  => 'Diameter',
                'spec_val'    => '115 mm',
                'rpm'         => '12,000',
                'material'    => 'Stainless Steel, Inox',
            ],
            [
                'category_id' => 'wire-brushes',
                'meta'        => 'Sikat Kawat',
                'title'       => 'End Brush Crimped – 50mm',
                'badge'       => null,
                'img'         => '',
                'desc'        => 'Sikat ujung kawat bergelombang untuk pembersihan lubang, rongga, dan celah sempit pada mould, dies, dan komponen presisi.',
                'spec_label'  => 'Diameter',
                'spec_val'    => '50 mm',
                'rpm'         => '4,500',
                'material'    => 'Semua Logam',
            ],

            // ── MOUNTED POINTS ───────────────────────────────────────────────
            [
                'category_id' => 'mounted-points',
                'meta'        => 'Mounted Points',
                'title'       => 'Mounted Point Silinder A – W20 × 25mm',
                'badge'       => null,
                'img'         => '',
                'desc'        => 'Batu gerinda bertangkai tipe silinder untuk penggerindaan dan deburring dalam lubang silindris, rongga cetakan, dan permukaan internal.',
                'spec_label'  => 'Ukuran',
                'spec_val'    => 'W20 × 25 mm',
                'rpm'         => '30,000',
                'material'    => 'Baja, Besi Cor, Mould',
            ],
            [
                'category_id' => 'mounted-points',
                'meta'        => 'Mounted Points',
                'title'       => 'Mounted Point Kerucut B – W10 × 20mm',
                'badge'       => 'Best Seller',
                'img'         => '',
                'desc'        => 'Batu gerinda bertangkai bentuk kerucut untuk finishing sudut dalam, chamfer, dan kontur radius pada komponen presisi dan dies.',
                'spec_label'  => 'Ukuran',
                'spec_val'    => 'W10 × 20 mm',
                'rpm'         => '45,000',
                'material'    => 'Tool Steel, Dies',
            ],
            [
                'category_id' => 'mounted-points',
                'meta'        => 'Mounted Points',
                'title'       => 'Mounted Point Bola C – Ø16mm',
                'badge'       => null,
                'img'         => '',
                'desc'        => 'Batu gerinda bertangkai kepala bulat untuk profiling dan finishing permukaan lengkung, weld root, dan area yang sulit dijangkau alat standar.',
                'spec_label'  => 'Diameter',
                'spec_val'    => 'Ø16 mm',
                'rpm'         => '38,000',
                'material'    => 'Baja, Stainless, Non-Ferro',
            ],
            [
                'category_id' => 'mounted-points',
                'meta'        => 'Mounted Points',
                'title'       => 'Diamond Mounted Point – Ø6mm Fine',
                'badge'       => 'Premium',
                'img'         => '',
                'desc'        => 'Mata gerinda bertangkai berlapis diamond untuk penggerindaan presisi tinggi pada karbida, keramik teknik, kaca, dan material super keras lainnya.',
                'spec_label'  => 'Diameter',
                'spec_val'    => 'Ø6 mm',
                'rpm'         => '50,000',
                'material'    => 'Carbide, Keramik, Kaca',
            ],

            // ── NON-WOVEN ────────────────────────────────────────────────────
            [
                'category_id' => 'non-woven',
                'meta'        => 'Non-Woven',
                'title'       => 'Unitized Wheel Non-Woven – 150×25mm',
                'badge'       => 'Best Seller',
                'img'         => '',
                'desc'        => 'Roda abrasif serat sintetis terintegrasi untuk finishing stainless, aluminium, dan tembaga. Menghasilkan efek brushed finish yang konsisten tanpa mengurangi dimensi.',
                'spec_label'  => 'Grade',
                'spec_val'    => 'Medium (6A)',
                'rpm'         => '3,500',
                'material'    => 'Stainless, Aluminium, Tembaga',
            ],
            [
                'category_id' => 'non-woven',
                'meta'        => 'Non-Woven',
                'title'       => 'Convolute Wheel Non-Woven – 200×50mm',
                'badge'       => null,
                'img'         => '',
                'desc'        => 'Roda non-woven berlapis ganda untuk deburring tepi, pemolesan, dan surface conditioning pada komponen stamping dan casting.',
                'spec_label'  => 'Grade',
                'spec_val'    => 'Fine (9A)',
                'rpm'         => '2,500',
                'material'    => 'Baja, Aluminium, Besi Cor',
            ],
            [
                'category_id' => 'non-woven',
                'meta'        => 'Non-Woven',
                'title'       => 'Hand Pad Non-Woven Maroon – 230×150mm',
                'badge'       => null,
                'img'         => '',
                'desc'        => 'Pad abrasif tangan berbasis serat nilon untuk scuffing, stripping cat, dan general purpose surface preparation secara manual tanpa mengikis logam dasar.',
                'spec_label'  => 'Grade',
                'spec_val'    => 'Coarse (Maroon)',
                'rpm'         => '-',
                'material'    => 'Semua Logam, Kayu, Plastik',
            ],
            [
                'category_id' => 'non-woven',
                'meta'        => 'Non-Woven',
                'title'       => 'Flap Brush Non-Woven – 115mm',
                'badge'       => 'New',
                'img'         => '',
                'desc'        => 'Kuas abrasif non-woven berputar untuk deburring dan surface conditioning pada sudut, tepi tajam, dan permukaan tidak rata setelah proses machining.',
                'spec_label'  => 'Diameter',
                'spec_val'    => '115 mm',
                'rpm'         => '12,200',
                'material'    => 'Baja Ringan, Aluminium',
            ],
        ];

        foreach ($products as $data) {
            Product::firstOrCreate(
                ['title' => $data['title'], 'category_id' => $data['category_id']],
                $data
            );
        }
    }
}
